replicaCount: 1

image:
  repository: nctiggy/cell-demo-app
  tag: "2.0.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000
  nodePort: 30080

database:
  host: "postgresql.virtual-machines.svc.cluster.local"
  port: 5432
  name: "cellops"
  user: "cellops"
  password: "cellops"

app:
  version: "2.0.0"
  connectionMethod: "overlay"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
