{{- if .Values.secretStore.create }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  provider:
    onepassword:
      connectHost: http://{{ .Values.connect.connect.host | default "onepassword-connect" }}.{{ .Release.Namespace }}.svc:{{ .Values.connect.connect.api.httpPort | default 8080 }}
      vaults:
        {{- toYaml .Values.secretStore.vaults | nindent 8 }}
      auth:
        secretRef:
          connectTokenSecretRef:
            name: {{ .Values.secretStore.tokenSecret.name }}
            namespace: {{ .Release.Namespace }}
            key: {{ .Values.secretStore.tokenSecret.key }}
{{- end }}
