apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cell-demo.fullname" . }}
  labels:
    {{- include "cell-demo.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
