apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "healthdata-viewer.fullname" . }}
  labels:
    {{- include "healthdata-viewer.labels" . | nindent 4 }}
data:
  DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
